Build using AdoptOpenJDK 8 & 11
lagom/akka-discovery-service-locator pull request #43
Opened 2019-02-05 21:23 UTC by marcospereira

2019-02-05 21:24 UTC, marcospereira commented on .travis.yml
> -  - name: tests
The tests will also run when publishing. Since they are pretty fast now, this should not have a significant impact.

2019-02-06 09:06 UTC, ignasi35 requested changes
I think the AdopOpenJDK looks correct but the `tests` section removal is wrong.

2019-02-06 09:06 UTC, ignasi35 commented on .travis.yml
> -  - name: tests
I'm confused. The `publish` stage only runs when the change was produced by a new tag

```
    if: repo = lagom/akka-discovery-service-locator AND tag =~ ^v
```

It seems to me like this PR makes the majority of builds a `noop`.

The idea of the condition for the stage `tests` (`NOT tag =~ ^v`) was exactly what you said: "Don't run the tests twice when publishing".

2019-02-06 15:42 UTC, ignasi35 approved these changes

2019-02-06 15:42 UTC, ignasi35 commented
@marcospereira told me how/why this will actually work on a call.

2019-02-06 15:59 UTC, ignasi35 commented
> @marcospereira told me how/why this will actually work on a call.

Meaning: I'm good with the PR. We're not merging it yet because there's a couple of issues with the release @marcospereira is investigating and we don't want to add more variable into the mix. Once the release is 100% stable we'll come back to this PR

2019-02-07 13:41 UTC, ignasi35 commented
@marcospereira I think the releasing is fixed (`0.0.12`succeeded). So I'm good moving forward the merge of this.

2019-02-07 15:35 UTC, renatocaval commented
Is that ok now?

2019-02-07 18:41 UTC, ignasi35 commented
> Is that ok now?

We want to expedite the resolution of the release process before merging this PR (which does quite a few changes in `.travis.yml`). I think it is OK now but wanted a last `+1` from @marcospereira

2019-02-07 19:22 UTC, octonato approved these changes

2019-02-07 19:22 UTC, renatocaval commented
@marcospereira, it's on you. Feel free to merge.

2019-02-07 20:05 UTC, merged